<a href="https://colab.research.google.com/github/Harsh-0-7/Kaggle-Competitions/blob/master/The_Boston_Housing_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Boston Housing Dataset

The Boston Housing Dataset is a derived from information collected by the U.S. Census Service concerning housing in the area of [Boston MA](http://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html). The following describes the dataset columns:

*  CRIM - per capita crime rate by town
*  ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
*  INDUS - proportion of non-retail business acres per town.
*  CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
*  NOX - nitric oxides concentration (parts per 10 million)
*  RM - average number of rooms per dwelling
*  AGE - proportion of owner-occupied units built prior to 1940
*  DIS - weighted distances to five Boston employment centres
*  RAD - index of accessibility to radial highways
*  TAX - full-value property-tax rate per \$10,000
*  PTRATIO - pupil-teacher ratio by town
*  B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
*  LSTAT - % lower status of the population
*  MEDV - Median value of owner-occupied homes in \$1000's [Target Variable]



In [ ]:
#Uploading Dataset
from google.colab import files
uploaded = files.upload()

In [29]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn


In [30]:
#Converting to DataFrame
dataset=pd.read_csv('housing.csv', delim_whitespace=' ', header=None,dtype='float32')

In [31]:
#Checking Few Records
dataset.head()

0     1     2    3   ...         10          11    12         13
0  0.00632  18.0  2.31  0.0  ...  15.300000  396.899994  4.98  24.000000
1  0.02731   0.0  7.07  0.0  ...  17.799999  396.899994  9.14  21.600000
2  0.02729   0.0  7.07  0.0  ...  17.799999  392.829987  4.03  34.700001
3  0.03237   0.0  2.18  0.0  ...  18.700001  394.630005  2.94  33.400002
4  0.06905   0.0  2.18  0.0  ...  18.700001  396.899994  5.33  36.200001

[5 rows x 14 columns]

In [32]:
dataset.describe()

0           1           2   ...          11          12          13
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613523   11.363636   11.136797  ...  356.674561   12.653064   22.532806
std      8.601545   23.322390    6.860355  ...   91.294838    7.141063    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377487    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440002   11.360000   21.200001
75%      3.677083   12.500000   18.100000  ...  396.225006   16.954999   25.000000
max     88.976196  100.000000   27.740000  ...  396.899994   37.970001   50.000000

[8 rows x 14 columns]

In [33]:
#Checking null value is present and dtype
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       506 non-null    float32
 1   1       506 non-null    float32
 2   2       506 non-null    float32
 3   3       506 non-null    float32
 4   4       506 non-null    float32
 5   5       506 non-null    float32
 6   6       506 non-null    float32
 7   7       506 non-null    float32
 8   8       506 non-null    float32
 9   9       506 non-null    float32
 10  10      506 non-null    float32
 11  11      506 non-null    float32
 12  12      506 non-null    float32
 13  13      506 non-null    float32
dtypes: float32(14)
memory usage: 27.8 KB


In [34]:
#Splitting into X and Y
input=dataset.iloc[:,:dataset.shape[1]-2]
output=dataset.iloc[:,dataset.shape[1]-1]
print(input.head())
print(output.head())

        0     1     2    3      4   ...      7    8      9          10          11
0  0.00632  18.0  2.31  0.0  0.538  ...  4.0900  1.0  296.0  15.300000  396.899994
1  0.02731   0.0  7.07  0.0  0.469  ...  4.9671  2.0  242.0  17.799999  396.899994
2  0.02729   0.0  7.07  0.0  0.469  ...  4.9671  2.0  242.0  17.799999  392.829987
3  0.03237   0.0  2.18  0.0  0.458  ...  6.0622  3.0  222.0  18.700001  394.630005
4  0.06905   0.0  2.18  0.0  0.458  ...  6.0622  3.0  222.0  18.700001  396.899994

[5 rows x 12 columns]
0    24.000000
1    21.600000
2    34.700001
3    33.400002
4    36.200001
Name: 13, dtype: float32


In [40]:
#Converting DataFrame to Tensor
x=input.to_numpy()
y=output.to_numpy()
x=torch.from_numpy(x)
y=torch.from_numpy(y)
#torch.reshape(x,(input.shape[0],input.shape[1]))
#torch.reshape(y,(output.shape[0],1))

print(x.shape)
print(y.shape)


torch.Size([506, 12])
torch.Size([506])


In [41]:
#For Converting DataFrame to TensorDataset
from torch.utils.data import TensorDataset

In [42]:
#TensorDataset allows us to access a small section of the training data
input=torch.tensor(x)
output=torch.tensor(y)

train_ds = TensorDataset(input, output)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


In [118]:
"""
  We'll create a DataLoader, which can split the data into batches of a predefined
 size while training. It also provides other utilities like shuffling and random sampling of the data.
"""
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [133]:
#Creating model of (Number of features Col x Number of Output Col)
model = nn.Linear(input.shape[1],1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2709, -0.2361,  0.2479, -0.0710,  0.1775,  0.1595, -0.1139,  0.0311,
          0.0993, -0.0782, -0.1596,  0.2152]], requires_grad=True)
Parameter containing:
tensor([-0.0251], requires_grad=True)


In [120]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0918, -0.2404,  0.2046,  0.2097, -0.2711, -0.1769,  0.0682, -0.2016,
          -0.2034, -0.2549, -0.2623,  0.0060]], requires_grad=True),
 Parameter containing:
 tensor([-0.2538], requires_grad=True)]

In [121]:
#Importing MSE Loss Function
import torch.nn.functional as F
loss_fn = F.mse_loss

In [122]:
#Caluclating Loss
loss = loss_fn(model(input), output)
print(loss.item())
from sklearn.model_selection import train_test_split


18410.712890625


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Using a target size (torch.Size([506])) that is different to the input size (torch.Size([506, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  


In [142]:
opt = torch.optim.SGD(model.parameters(), lr=1e-9)

In [140]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            #print(yb.shape)
            # 2. Calculate loss
            #yb = yb[:-1]
            #loss = (pred - yb.mean()) / (yb.std() + 1e-9)
            #loss.reshape(pred.shape[0], 1)
            # 3. Compute gradients"
            loss=loss_fn(pred,yb)
            loss.backward()
            #print(yb)
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [143]:
fit(100, model, loss_fn, opt, train_dl)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.


Epoch [10/100], Loss: 20071.5469
Epoch [20/100], Loss: 2199.0322
Epoch [30/100], Loss: 4538.7017
Epoch [40/100], Loss: 4364.5713
Epoch [50/100], Loss: 2152.7903
Epoch [60/100], Loss: 294.0473
Epoch [70/100], Loss: 1840.9786
Epoch [80/100], Loss: 304.1095
Epoch [90/100], Loss: 27.2005
Epoch [100/100], Loss: 0.0010
